# output.json fields
id_create: md5 # can be md5 | shortId | uniqId (defaults to uniqId)
upload:
  s3_directory: 'samples'
  s3_bucket: 'upload-test-dan'
  cloudfront_url: '' # with https://
# will be included in database (optional)
metadata:
  longitude: null
  latitude: null
  date: null
sizes:
  # "small" image
  small:
    width: 200
    height: 200
    fit: cover # can be cover (crop) | inside (no crop)
    quality: 100
    sharpen: 
      sigma: 0.6
      flat: 1.0
      jagged: 0.9
  # "medium" image
  medium:
    width: 640
    height: 480
    fit: inside # can be cover (crop) | inside (no crop)
    quality: 95
    sharpen: 
      sigma: 0.8
      flat: 1.0
      jagged: 0.9